### ISSUE TITLE
Menu bar icon should show the current theme

### ISSUE THREAD

**Issue by deandmx** [HarshilShah/Nocturnal#4]
In dark mode the menubar icon is a sun and in light mode it's the moon. The icon should show what the current state is, rather than the alternative theme. 

The default system menubar icons show the current state. For example, sound, wifi, airplay, time, battery etc all show the current state of the thing they control.

**Comment by HarshilShah** [comment]
While it’s true that system menubar icons show the current state, it’s worth noting that for all of those, there’s no way you can intuit that current state in all cases. Maybe if you’re getting network errors or the volume is too soft or loud, sure, but the state isn’t always obvious.

Whereas it should be readily apparent even just looking at the menubar alone whether your current theme is light or dark.

So with current state apparent anyways, I think it makes more sense to click the moon to enter dark mode and sun to enter light mode. If I’m looking for a button to enter dark mode, tapping a moon just seems more obvious than a sun. Obviously you can have a different opinion, but this is just how I feel.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
