### ISSUE TITLE
Brew Cask Formula

### ISSUE THREAD

**Issue by hadig** [HarshilShah/Nocturnal#5]
Hi, can you make an official brew formula for your utility for easy installation.

**Comment by HarshilShah** [comment]
Thanks for this idea! I haven’t published anything view Homebrew yet but this definitely sounds doable. I’ll look into it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HarshilShah** [comment]
So a PR is up on homebrew-cask https://github.com/Homebrew/homebrew-cask/pull/53585. Here’s hoping that it gets merged quickly 🤞🏽

**Comment by HarshilShah** [comment]
And it’s merged! 🎉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
