### ISSUE TITLE
Nocturnal detected as malware on Catalina Beta 5

### ISSUE THREAD

**Issue by JS1010111** [HarshilShah/Nocturnal#7]
macOS 10.15 Beta 5 (19A526h)

![Screen Shot 2019-08-03 at 4 14 26 pm](https://user-images.githubusercontent.com/10931029/62416028-f69dac00-b609-11e9-8109-573106c12529.png)

**Comment by HarshilShah** [comment]
Huh, interesting. I have a hunch this might be related to the recent notarisation changes. I’ll take a look and see if that fixes the error. Thanks for the heads up!

**Comment by LinusGeffarth** [comment]
Hey, seeing a similar issue and cannot open the app. Any updates on this yet?

**Comment by mflint** [comment]
You can workaround this by:
* open the /Applications folder (or wherever you have Nocturnal installed)
* right-click (or control-click) on Nocturnal.app
* select "Get Info"
* select "Override Malware Protection"

**Comment by jaredatron** [comment]
same!

**Comment by jaredatron** [comment]
Alternative: https://github.com/joshjon/nocturnal
